# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Install dependecies
        run: npm run install:client

      # Runs a set of commands using the runners shell
      - name: Install eslint
        run: npm install -g eslint

      # Runs a set of commands using the runners shell
      - name: Run eslint
        run: npm run lint:client
  lint-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Runs a single command using the runners shell
      - name: Install dependecies
        run: npm run install:server

      # Runs a set of commands using the runners shell
      - name: Install eslint
        run: npm install -g eslint
      - name: Install eslint plugin
        run: npm install eslint-plugin-import@latest --save-dev
      # Runs a set of commands using the runners shell
      - name: Run eslint
        run: npm run lint:server
